name: doctests

on:
  push:
    branches:
      - main

jobs:
  doctests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Build treams
      run: python -m pip install -e .
    - name: Run doctests
      run: |
        python -m pip install treams[docs,io]
        sphinx-build -b doctest docs docs/_build/doctest
