name: doctests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  doctests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Build treams
      run: python -m pip install "numpy<2" -e .[docs,io]
    - name: Install requirements for gmsh
      run: |
        sudo apt-get update
        sudo apt-get -y install libglu1 libxcursor-dev libxft2 libxinerama1 libfltk1.3-dev libfreetype6-dev libgl1-mesa-dev
    - name: Run doctests
      run: |
        TZ=UTC sphinx-build -b doctest docs docs/_build/doctest
